"""Changing Post Table

Revision ID: 6484880a8959
Revises: 
Create Date: 2020-06-01 21:16:31.122824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6484880a8959'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('Behaviour', sa.String(length=1000), nullable=True))
    op.add_column('post', sa.Column('Cleanliness', sa.String(length=1000), nullable=True))
    op.add_column('post', sa.Column('Description', sa.String(length=100), nullable=False))
    op.add_column('post', sa.Column('FQ', sa.String(length=1000), nullable=True))
    op.add_column('post', sa.Column('Ingredients', sa.String(length=1000), nullable=True))
    op.add_column('post', sa.Column('Rating', sa.String(length=1000), nullable=True))
    op.add_column('post', sa.Column('Services', sa.String(length=1000), nullable=True))
    op.add_column('post', sa.Column('Steps', sa.String(length=1000), nullable=True))
    op.add_column('post', sa.Column('Type', sa.String(length=1000), nullable=True))
    op.drop_column('post', 'Content1')
    op.drop_column('post', 'Content3')
    op.drop_column('post', 'Content2')
    op.alter_column('user', 'imgId',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'5ecfcbf80ae3f2197bbbb0ed'"))
    op.create_unique_constraint(None, 'user', ['Email'])
    op.create_unique_constraint(None, 'user', ['Username'])
    op.create_unique_constraint(None, 'user', ['Password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'imgId',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'5ecfcbf80ae3f2197bbbb0ed'"))
    op.add_column('post', sa.Column('Content2', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('post', sa.Column('Content3', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('post', sa.Column('Content1', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('post', 'Type')
    op.drop_column('post', 'Steps')
    op.drop_column('post', 'Services')
    op.drop_column('post', 'Rating')
    op.drop_column('post', 'Ingredients')
    op.drop_column('post', 'FQ')
    op.drop_column('post', 'Description')
    op.drop_column('post', 'Cleanliness')
    op.drop_column('post', 'Behaviour')
    # ### end Alembic commands ###
